#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : codec2
Version  : 0.8
Release  : 1
URL      : https://sourceforge.net/code-snapshots/svn/f/fr/freetel/code/freetel-code-r3650-codec2-branches-0.8.zip
Source0  : https://sourceforge.net/code-snapshots/svn/f/fr/freetel/code/freetel-code-r3650-codec2-branches-0.8.zip
Summary  : A speech codec for 2400 bit/s and below
Group    : Development/Tools
License  : LGPL-2.1
Requires: codec2-bin = %{version}-%{release}
Requires: codec2-lib = %{version}-%{release}
Requires: codec2-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : pkgconfig(samplerate)
BuildRequires : pkgconfig(speexdsp)
BuildRequires : subversion

%description
--------------
Codec 2 is an open source (LGPL 2.1) low bit rate speech codec:
http://rowetel.com/codec2.html

%package bin
Summary: bin components for the codec2 package.
Group: Binaries
Requires: codec2-license = %{version}-%{release}

%description bin
bin components for the codec2 package.


%package dev
Summary: dev components for the codec2 package.
Group: Development
Requires: codec2-lib = %{version}-%{release}
Requires: codec2-bin = %{version}-%{release}
Provides: codec2-devel = %{version}-%{release}
Requires: codec2 = %{version}-%{release}

%description dev
dev components for the codec2 package.


%package lib
Summary: lib components for the codec2 package.
Group: Libraries
Requires: codec2-license = %{version}-%{release}

%description lib
lib components for the codec2 package.


%package license
Summary: license components for the codec2 package.
Group: Default

%description license
license components for the codec2 package.


%prep
%setup -q -n freetel-code-r3650-codec2-branches-0.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556917395
mkdir -p clr-build
pushd clr-build
export LDFLAGS="${LDFLAGS} -fno-lto"
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1556917395
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/codec2
cp COPYING %{buildroot}/usr/share/package-licenses/codec2/COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/c2dec
/usr/bin/c2demo
/usr/bin/c2enc
/usr/bin/c2sim
/usr/bin/drs232
/usr/bin/drs232_ldpc
/usr/bin/fdmdv_demod
/usr/bin/fdmdv_get_test_bits
/usr/bin/fdmdv_interleave
/usr/bin/fdmdv_mod
/usr/bin/fdmdv_put_test_bits
/usr/bin/fec_dec
/usr/bin/fec_enc
/usr/bin/fm_demod
/usr/bin/fsk_mod
/usr/bin/insert_errors

%files dev
%defattr(-,root,root,-)
/usr/include/codec2/codec2.h
/usr/include/codec2/codec2_cohpsk.h
/usr/include/codec2/codec2_fdmdv.h
/usr/include/codec2/codec2_fifo.h
/usr/include/codec2/codec2_fm.h
/usr/include/codec2/codec2_ofdm.h
/usr/include/codec2/comp.h
/usr/include/codec2/comp_prim.h
/usr/include/codec2/freedv_api.h
/usr/include/codec2/freedv_api_internal.h
/usr/include/codec2/fsk.h
/usr/include/codec2/golay23.h
/usr/include/codec2/kiss_fft.h
/usr/include/codec2/modem_stats.h
/usr/include/codec2/varicode.h
/usr/include/codec2/version.h
/usr/lib64/libcodec2.so
/usr/lib64/pkgconfig/codec2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcodec2.so.0.8

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/codec2/COPYING
